### ISSUE TITLE
global: major rewrite

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-collections#32]
- [x] cleaning models (Collection, Collectionname, CollectionCollection, FacetCollection)
- [ ] REST API `/api/collections` -> list collections user can view (parent, child links)
- [x] depends on `invenio-search` and `invenio-records` - patch and re-index on collection and collection_collection table updates
- [x] port https://github.com/inveniosoftware/invenio-records/blob/9cd7880e95e5ae399d403273399086cd07e4652a/invenio_records/recordext/functions/get_record_collections.py
- [x] percolators - `COLLECTIONS_PERCOLATOR_INDEXES = None or ['records-books', 'records-papers']` (`None` - uses local matcher, `list` - uses elastic client to retrieve collection names) 
- [x] access caches
- [x] port slugify for usage as template name

--
cc @egabancho @drjova

**Comment by egabancho** [comment]
cc @hachreak

**Comment by jirikuncar** [comment]
Closed via #33, #34 and 0ec2a7ea308d61dadd6aaff713ea3a98dbdf77d5.
